version: '3.0.1'

services:
    db:
        image: postgres:13.1
        privileged: true
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres
    app:
        privileged: true
        build: ./app
        command: bash -c "
            ./wait-for-postgres.sh db && python3 telegram_bot.py"
        depends_on:
            - db