version: '3.0'

volumes:
    postgres-data:

services:
    db:
        image: postgres:14.4
        privileged: true
        restart: always
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres

    app:
        build:
            context: ./app/
        privileged: true
        depends_on:
            - db
        command: bash -c "
            python run.py"